### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by raeedcho** [ahwillia/tensortools#12]
I may very well not be doing this right, but I had a few issues installing tensortools. I have it installed now, but I thought I'd open an issue here in case I'm not the only one with these issues. For reference, I was trying this under Python 3.6.

I first tried installing with `pipenv install tensortools`, which came back with the error

> Could not find a version that satisfies the requirement tensortools (from versions: )  
> No matching distribution found for tensortools

`pip install tensortools` gave the same result. It seemed like tensortools wasn't compatible with this version of Python, but I couldn't find any information about what version I should be using for this.

I then just cloned the git repository into my directory and tried running setup.py, which resulted in:

> Traceback (most recent call last):
>   File "setup.py", line 3, in <module>
>     from Cython.Build import cythonize
> ModuleNotFoundError: No module named 'Cython'

I assume this is because Cython is referenced before setup.py mentions that it's an installation requirement, but I'm not familiar enough with Python packages to be sure. In any case, once I installed Cython (pipenv install Cython), the installation using setup.py worked.

Could anyone tell me if I did anything wrong here? Thanks!

**Comment by ahwillia** [comment]
I think you did everything right! I will look into this as soon as I can (maybe this weekend).

**Comment by erichson** [comment]
@RaeedChowdhury could you try to install tensortools via git:

```
git clone git@github.com:ahwillia/tensortools.git
```
then change to the folder and run
```
python setup.py install
python setup.py test
```

**Comment by RaeedChowdhury** [comment]
@erichson Just tried this, and I got the same error ("No module named 'Cython'")

**Comment by erichson** [comment]
@RaeedChowdhury do you use Anaconda Python 3.6? Otherwise, you need to install several packages by hand, i.e., 
```
pip install Cython
```
Then try to install ``tensortools``` again.

**Comment by RaeedChowdhury** [comment]
@erichson Ah, I didn't realize that tensortools assumed an Anaconda 3.6 environment. No, I use my own Python installation. Is this also the reason that `pip install tensortools` didn't work?

Thanks for the solution; I mentioned in the initial post that this is how I got it to work, but I think I didn't make it clear enough. I think Cython is the only package that needs installation manually; as far as I can tell, every other package dependency is taken care of by setup.py. In any case, my reason for opening this issue is for anyone else who might be having the same installation issues I encountered.

Do you think there's any way to make sure Cython gets installed as a dependency before it's referenced by setup.py? The easiest solution would probably be to update the docs to make sure Cython is installed before installing tensortools and/or point to this Github issue for anyone not using Anaconda.

The other (non-Anaconda) issue I should mention is that I had to make sure tk and tcl packages were installed on my system before creating my Python environment. That is obviously not a problem with tensortools, but just another thing to note for people installing this package outside of Anaconda.

Anyway, thanks for the prompt responses!

**Comment by erichson** [comment]
@RaeedChowdhury sorry got it. I should have read your initial post more carefully... :)

I think we can fix this in the one or other way. In any case, thank you for pointing this issue out.

Best,
Ben

**Comment by LuLing06** [comment]
When I did 'pip install git+https://github.com/ahwillia/tensortools' in commend prompt, I got an error message" Error [WinError 2] The system could not find the specified file。 while executing command git clone -q https://github.com/ahwillia/tensortools C:\Users\13120\AppData\Local\Temp\pip-req-build-z4r3wdju Cannot find command 'git' - do you have 'git' installed and in your PATH?'

Can you tell me how to fix it?

**Comment by ahwillia** [comment]
It looks like you don't have `git` installed. Either install `git` (see here) or try:

```
pip install https://github.com/ahwillia/tensortools/zipball/master
```

Which is alternative way to install without git.

**Comment by LuLing06** [comment]
> @RaeedChowdhury could you try to install tensortools via git:
> 
> ```
> git clone git@github.com:ahwillia/tensortools.git
> ```
> then go to the folder and run
> 
> ```
> python setup.py install
> python setup.py test
> ```

where I can run this code? in command prompt or git cmd?

**Comment by ahwillia** [comment]
I think `git cmd` should be fine to run these commands, but I use a mac so I'm not totally sure. Can you try upgrading setuptools and let us know if the problem persists?

```
pip install -U setuptools
```

**Comment by LuLing06** [comment]
> I think `git cmd` should be fine to run these commands, but I use a mac so I'm not totally sure. Can you try upgrading setuptools and let us know if the problem persists?
> 
> ```
> pip install -U setuptools
> ```

Thanks! It works, another question is about the example. say if I have a categorical (columns) dataframe in python(timestamp, land feature), each categorical feature has different subset(e.g. there are three types in land feature:A,B,C). And the row is the user id (observation). So, I think it is a three order tensor(user id, timestamp, land feature). Could you please tell me how to transfer the original dataframe into tensor and I want to take the frequency as the weight for each cell ( e.g. the combination of userid= '1', timestamep='6am' and land feature='A ' has 6 observation, so the value of this cell is 6 )?

Thanks very much!
Best,

**Comment by ahwillia** [comment]
Closing as installation issue was fixed by upgrading setuptools.
