### ISSUE TITLE
Cross validation / running on held-out data

### ISSUE THREAD

**Issue by klmcguir** [ahwillia/tensortools#13]
I was hoping to try and fit models with empty data in the tensor and to try performing CV as you did in your paper. Is this possible yet? I see that training and test sets are mentioned in partition in visualization.py. Is there an easy way to run this with nans, etc? Please let me know!

**Comment by ahwillia** [comment]
Apologies, I haven't gotten around to this since refactoring the code. It is buried in the old commit logs if you need it fast: https://github.com/ahwillia/tensortools/commit/36bc8d26392f379194fd4ddae85fe5ebce262478

I'll try to get this back into the codebase soon. If you're willing to use Matlab, there is a method [`cp_wopt`](https://www.tensortoolbox.org/cp_wopt_doc.html) for fitting tensor decompositions with missing / held out data in Sandia Lab's [tensortoolbox](https://www.tensortoolbox.org/index.html).

**Comment by klmcguir** [comment]
Awesome thanks so much! I will try messing around with your old version and cp_opt! Just to check, passing the current algorithm a masked matrix will not be equivalent running the approximation for ALS  on a masked/held-out tensor?

**Comment by ahwillia** [comment]
No definitely not on the main branch at the moment.

**Comment by klmcguir** [comment]
Great. Thank you!

**Comment by ahwillia** [comment]
I just added support for fitting CP decomposition with missing data: 9d93938769cf1d59e77575bfc05efbf154a374f4

And docs are here: https://tensortools-docs.readthedocs.io/en/latest/algorithms/tensortools.mcp_als.html

You will have to pull the latest code:

```
git checkout master
git pull
python setup.py install
```

Let me know if you run into any other problems either here or by email. Hope this helps!

**Comment by klmcguir** [comment]
Awesome thank you so much! I will definitely let you know if I run into any issues!
