### ISSUE TITLE
Variance explained

### ISSUE THREAD

**Issue by pietromarchesi** [ahwillia/tensortools#17]
Is there a way to return/access the lambdas (explained variance) of the different factors?

**Comment by ahwillia** [comment]
In PCA, since the factors are orthogonal, the variance explained by each factor is unique. In tensor decomposition, the factors aren't orthogonal so the "variance explained" needs to be interpreted with care.

Nonetheless you can compute the size of each factor (the lambdas) which may give you a sense of the relative importance of each factor. See equation 3.3 of [Kolda & Bader](http://www.kolda.net/publication/TensorReview.pdf).

Using nonnegative tensor decompositions makes it easier to interpret the lambdas because you don't have situations where two large factors that are correlated with opposite signs cancel each other out.

There is now a helper function to compute the lambdas for you. See 2cfa9db106c45d73f7837f41d4bea12275694532. Thanks for opening this issue.

**Comment by pietromarchesi** [comment]
Great, thanks!
